#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
---
version: '3.3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ${artifactId}-db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - backend

  ${artifactId}:
    depends_on:
      - db
    build: .
    image: ${artifactId}:latest
    ports:
      - '8080:8080'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-data: