#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/${artifactId}-db
    username: postgres
    password: pass
  messages:
    basename: i18n.messages

info:
  name: ${projectName}
  more.detail: ${projectDescription}

management.endpoints.web.exposure.include:
  - info
  - health
  - prometheus
